// Generated by CoffeeScript 1.9.3
(function() {
  var exports;

  exports = window;

  Array.prototype.shuffle = function() {
    return this.sort(function() {
      return 0.5 - Math.random();
    });
  };

  $(function() {
    var $slideshow;
    $slideshow = $('#slideshow');
    return $.getJSON("projects.json", function(_projects) {
      var $image, $project, $title, i, j, project, projects, ref, results;
      projects = _projects.shuffle();
      $slideshow.addClass("size-" + projects.length);
      results = [];
      for (i = j = 0, ref = projects.length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        project = projects[i];
        $project = $("<li></li>");
        $image = $("<span></span>").css('background-image', "url(images/" + project.image + ")");
        $title = $("<h2>" + project.title + "</h2>");
        $image.appendTo($project);
        $title.appendTo($project);
        results.push($project.appendTo($slideshow));
      }
      return results;
    });
  });

}).call(this);
